### ISSUE TITLE
Feature Request: Uptime in seconds

### ISSUE THREAD

**Issue by alexrjs** [cavaliercoder/rpi_export#1]
I like the minimalistic selection of values. But I like to see the uptime as well, for that I have to install the prometheus node_exporter to get the boot_time for that. Since I'm not a go programmer I can't add it myself. Would it be possible to add a boot_time_in_seconds like the node_exporter from prometheus?

**Comment by cavaliercoder** [comment]
This is a perfectly reasonable request but this tool doesn't intend to duplicate any functionality of the original node_exporter. or any other exporter. By design, they should be used to complement each other. I'd recommend installing the node_exporter.

**Comment by alexrjs** [comment]
Very good reason, thanks for explaining. Nevertheless, I don't want the node_exporter, TMI... I used chatGPT and added it myself with my little GOLANG I know, but it works and I have my uptime. I also thinned out your code since it still had TMI. I want a very lean node_exporter for the raspi k3s cluster. But many thanks for sharing and giving me a good starting point. d
